project:
  type: book
  output-dir: _book

book:
  title: "Entre o Pós-Abolição e a História Digital"
  subtitle: "usos e sentidos do termo pós-abolição nos Simpósios Nacionais de História da ANPUH (2013 - 2019)"
  author: "Priscila Valverde Silveira"
  date: "19/06/2022"
  chapters:
    - index.qmd
    - resumo.qmd
    - agradecimento.qmd
    - intro.qmd
    - cap1.qmd
    - cap2.qmd
    - cap3.qmd
    - conclusao.qmd
    - references.qmd
  appendices:
    - lists.qmd
    - imgs.qmd
  sharing: 
    - twitter
    - facebook
  downloads: 
    - pdf
    - epub
  page-footer:
    center: 
      - text: "Copyright 2022, Priscila Valverde Silveira"
        href: "https://github.com/priscilavalverdes/TCC-Pos-abolicao"
  
bibliography: references.bib

format:
  html:
    theme: 
        light: flatly
        dark: darkly
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
  epub:
    documentclass: book
    epub-cover-image: cover.png





